accessControl:
  salt: gUocy8QZC6c8DceUtYDlmAadW5siL03P
api:
  key: 9E5BA439FF304E1E98E9CC97121F5B7F
appearance:
  color: blue
  components:
    order:
      sidebar:
      - connection
      - state
      - plugin_automaticshutdown
      - files
  name: ToolChanger Motion System
controls:
- children:
  - command: AUTO_BED_MAPPING
    name: Auto Bed Mapping
    type: command
  - command: MOVE_NOZZLE_TO_BED
    name: Move Nozzle to Bed
    type: command
  - command: TOO_LOW
    name: Too Low
    type: command
  - command: TOO_HIGH
    name: Too High
    type: command
  - command: SAVE_AND_HOME
    name: Save & Home
    type: command
  layout: vertical
  name: Bed Leveling & Nozzle Height
  type: section
- children:
  - children:
    - command: CALIBRATE_PROBE_OFFSET
      name: Calibrate Probe Offset
    layout: horizontal
  - children:
    - command: POINT_TOO_LOW
      name: Offset Too Low
      type: command
    - command: TESTZ Z=+
      name: +
      type: command
    layout: horizontal
  - children:
    - command: POINT_TOO_HIGH
      name: Offset Too High
      type: command
    - command: TESTZ Z=-
      name: '-'
      type: command
    layout: horizontal
  - command: SAVE_MANUAL_CALIBRATE
    name: Save Probe Calibration
    type: command
  - command: ABORT_CALIBRATE
    name: Keep Previous Calibration
    type: command
  layout: vertical
  name: Touch Probe Calibration (advanced)
  type: section
feature:
  keyboardControl: false
  modelSizeDetection: false
  sdSupport: false
folder:
  timelapse_tmp: /home/pi/.octoprint/tlapse/tmp
plugins:
  _disabled:
  - softwareupdate
  - announcements
  - forcelogin
  - ipOnConnect
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1551867600
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1549966200
      _plugins:
        read_until: 1551657600
      _releases:
        read_until: 1544449800
  bedlevelvisualizer:
    command: '@BEDLEVELVISUALIZER BED_MESH_OUTPUT'
    save_mesh: false
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
    upnpUuid: a772115a-7360-4c0c-ae17-2643777310ef
  errortracking:
    unique_id: e8a21947-f6a8-44a2-b35e-48ab1e888604
  klipper:
    _config_version: 2
    macros:
    - macro: M112
      name: E-STOP
      sidebar: true
      tab: false
    - macro: AUTO_BED_MAPPING
      name: Auto Bed Mapping
      sidebar: true
      tab: false
    - macro: DELTA_CALIBRATE METHOD=MANUAL
      name: Start Advanced Calibration
      sidebar: false
      tab: true
    - macro: TESTZ Z=-
      name: z+
      sidebar: false
      tab: true
    - macro: TOO_HIGH
      name: Too High
      sidebar: true
      tab: true
    - macro: TESTZ Z=+
      name: z-
      sidebar: false
      tab: true
    - macro: TOO_LOW
      name: Too Low
      sidebar: true
      tab: true
    - macro: ACCEPT
      name: Just Right
      sidebar: false
      tab: true
    - macro: SAVE_AND_HOME
      name: Save and Home
      sidebar: true
      tab: true
    probe:
      height: '0.1'
      lift: '25'
      points:
      - name: point-1
        x: 0
        y: 0
      - name: point-#
        x: '50'
        y: '50'
        z: 0
      speed_xy: '4000'
      speed_z: '4000'
  navbartemp:
    displayRaspiTemp: false
  softwareupdate:
    _config_version: 6
  themeify:
    customRules:
    - enabled: false
      rule: background-color
      selector: .navbar-inner
      value: '#2f3136'
    - enabled: false
      rule: background-color
      selector: .accordion
      value: '#2f3136'
    - enabled: true
      rule: width
      selector: .span8
      value: 70%
    - enabled: true
      rule: width
      selector: .span4
      value: 25%
    - enabled: true
      rule: left-margin
      selector: .row
      value: '0'
    enableCustomization: true
    theme: material_ui_light
  tracking:
    enabled: false
    unique_id: cc18194d-782f-48b0-ac4e-5642f1a4965d
printerProfiles:
  default: deltamaker
serial:
  abortHeatupOnCancel: false
  additionalPorts:
  - /tmp/printer
  autoconnect: true
  baudrate: 250000
  disconnectOnErrors: false
  ignoreErrorsFromFirmware: true
  logPositionOnCancel: true
  port: /tmp/printer
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: yATztxv9FKCl6Rf6bT8gHpdF5umPouH2
  seenWizards:
    bedlevelvisualizer: null
    corewizard: 3
    cura: null
    tracking: null
system: {}
temperature:
  profiles:
  - bed: 0
    chamber: null
    extruder: 230
    name: DM-PLA
  - bed: 0
    chamber: null
    extruder: 100
    name: UNLOAD
  - bed: 95
    chamber: null
    extruder: 250
    name: DM-PETG
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://127.0.0.1:8080/?action=snapshot
  stream: /webcam/?action=stream
  streamRatio: '4:3'
  timelapse:
    fps: 25
    options:
      minDelay: 5.0
      retractionZHop: 0.75
    postRoll: 5
    type: zchange
  watermark: false
