accessControl:
  salt: gUocy8QZC6c8DceUtYDlmAadW5siL03P
api:
  key: 9E5BA439FF304E1E98E9CC97121F5B7F
appearance:
  color: blue
  components:
    order:
      sidebar:
      - connection
      - state
      - plugin_automaticshutdown
      - files
  name: DeltaMaker R2 Dev
controls:
- children:
  - command: AUTO_BED_MAPPING
    name: Auto Bed Mapping
    type: command
  - command: MOVE_NOZZLE_TO_BED
    name: Move Nozzle to Bed
    type: command
  - command: TOO_LOW
    name: Too Low
    type: command
  - command: TOO_HIGH
    name: Too High
    type: command
  - command: SAVE_AND_HOME
    name: Save & Home
    type: command
  layout: vertical
  name: Bed Leveling & Nozzle Height
  type: section
- children:
  - command: START_MANUAL_CALIBRATE
    name: Start Calibration
    type: command
  - children:
    - command: POINT_TOO_LOW
      name: Point Too Low
      type: command
    - command: TESTZ Z=+
      name: +
      type: command
    layout: horizontal
  - children:
    - command: POINT_TOO_HIGH
      name: Point Too High
    - command: TESTZ Z=-
      name: '-'
    layout: horizontal
  - command: ACCEPT_POINT
    name: Next Calibration Point
    type: command
  - command: SAVE_MANUAL_CALIBRATE
    name: SAVE
    type: command
  - command: ABORT_CALIBRATE
    name: Discard Changes
    type: command
  layout: vertical
  name: Touch Probe Calibration (advanced)
  type: section
feature:
  keyboardControl: false
  modelSizeDetection: false
  sdSupport: false
plugins:
  _disabled:
  - softwareupdate
  - announcements
  - forcelogin
  - ipOnConnect
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1551867600
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1549966200
      _plugins:
        read_until: 1551657600
      _releases:
        read_until: 1544449800
  bedlevelvisualizer:
    command: '@BEDLEVELVISUALIZER BED_MESH_OUTPUT'
    save_mesh: false
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
  klipper:
    _config_version: 2
    macros:
    - macro: M112
      name: E-Stop
      sidebar: true
      tab: true
    - macro: M118
      name: Display on Host
      sidebar: true
      tab: true
    probe:
      height: '0.1'
      lift: '25'
      points:
      - name: point-1
        x: 0
        y: 0
      - name: point-#
        x: '50'
        y: '50'
        z: 0
      speed_xy: '4000'
      speed_z: '4000'
  navbartemp:
    displayRaspiTemp: false
  softwareupdate:
    _config_version: 6
  themeify:
    customRules:
    - enabled: false
      rule: background-color
      selector: .navbar-inner
      value: '#2f3136'
    - enabled: false
      rule: background-color
      selector: .accordion
      value: '#2f3136'
    - enabled: true
      rule: width
      selector: .span8
      value: 70%
    - enabled: true
      rule: width
      selector: .span4
      value: 25%
    - enabled: true
      rule: left-margin
      selector: .row
      value: '0'
    enableCustomization: true
    theme: material_ui_light
  tracking:
    enabled: false
printerProfiles:
  default: _default
serial:
  additionalPorts:
  - /tmp/printer
  autoconnect: true
  baudrate: 250000
  disconnectOnErrors: false
  port: /tmp/printer
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
  firstRun: false
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
  secretKey: yATztxv9FKCl6Rf6bT8gHpdF5umPouH2
  seenWizards:
    bedlevelvisualizer: null
    corewizard: 3
    cura: null
    tracking: null
system: {}
temperature:
  profiles:
  - bed: 0
    extruder: 230
    name: DM-PLA
  - bed: 0
    extruder: 100
    name: UNLOAD
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://127.0.0.1:8080/?action=snapshot
  stream: ''
  watermark: false
